"""Domain-specific exception classes."""

from pysrc.core.errors.base import (
    AggregateError,
    APIConnectionError,
    ConfigValidationError,
    DataDriftError,
    DataError,
    DataFetchError,
    DataPreconditionError,
    DataTimeoutError,
    DataValidationError,
    FileFormatError,
    GenericDataError,
    IBKRConnectionError,
    InvalidInputError,
    ModelCheckpointError,
    ModelInferenceError,
    ModelTrainingError,
    NoDataError,
    PITViolationError,
    PreprocessingError,
    SchemaValidationError,
    StalenessError,
    StatisticalTestError,
    StreamConnectionError,
    TradingExecutionError,
    UnsupportedPlan,
)

__all__ = [
    "APIConnectionError",
    "AggregateError",
    "ConfigValidationError",
    "DataDriftError",
    "DataError",
    "DataFetchError",
    "DataPreconditionError",
    "DataTimeoutError",
    "DataValidationError",
    "FileFormatError",
    "GenericDataError",
    "IBKRConnectionError",
    "InvalidInputError",
    "ModelCheckpointError",
    "ModelInferenceError",
    "ModelTrainingError",
    "NoDataError",
    "PITViolationError",
    "PreprocessingError",
    "SchemaValidationError",
    "StalenessError",
    "StatisticalTestError",
    "StreamConnectionError",
    "TradingExecutionError",
    "UnsupportedPlan",
]
