#!/usr/bin/env python3
"""Generate tracked-file bloat inventory report for cleanup planning."""

from __future__ import annotations

import argparse
import collections
import hashlib
import subprocess
from pathlib import Path

BLOCKED_PREFIXES = (
    ".poetry-cache/",
    ".venv",
    ".mypy_cache/",
    ".pytest_cache/",
    ".claude/worktrees/",
    ".codex",
    ".cursor/",
    "node_modules/",
    "htmlcov/",
    ".cache/",
    "target/",
    "docs/out/",
)


def _git_ls_files() -> list[str]:
    proc = subprocess.run(["git", "ls-files"], capture_output=True, text=True, check=True)
    return [line.strip() for line in proc.stdout.splitlines() if line.strip()]


def _normalize(path: str) -> str:
    return path.replace("\\", "/")


def _hash_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            chunk = f.read(1024 * 1024)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def _human_mb(size_bytes: int) -> str:
    return f"{size_bytes / (1024 * 1024):.2f}"


def generate_report(output_path: Path) -> None:
    tracked = _git_ls_files()
    file_rows: list[tuple[str, int]] = []
    by_dir: dict[str, int] = collections.defaultdict(int)
    by_hash: dict[str, list[str]] = collections.defaultdict(list)
    blocked: list[str] = []
    candidate_tier_c: list[tuple[str, int]] = []

    for rel in tracked:
        path = Path(rel)
        if not path.is_file():
            continue
        size = path.stat().st_size
        file_rows.append((rel, size))
        top = _normalize(rel).split("/", 1)[0]
        by_dir[top] += size
        digest = _hash_file(path)
        by_hash[digest].append(rel)

        norm = _normalize(rel)
        if any(norm.startswith(prefix) for prefix in BLOCKED_PREFIXES):
            blocked.append(rel)
        if size > 2 * 1024 * 1024 and path.suffix.lower() in {".json", ".csv", ".parquet"}:
            candidate_tier_c.append((rel, size))

    largest_files = sorted(file_rows, key=lambda item: item[1], reverse=True)[:100]
    largest_dirs = sorted(by_dir.items(), key=lambda item: item[1], reverse=True)[:30]
    dup_hashes = [(digest, paths) for digest, paths in by_hash.items() if len(paths) > 1]
    dup_hashes.sort(key=lambda item: len(item[1]), reverse=True)

    report_lines: list[str] = []
    report_lines.append("# Repo Bloat Inventory Report")
    report_lines.append("")
    report_lines.append("Generated by `devtools/repo_bloat_inventory.py` against tracked files.")
    report_lines.append("")
    report_lines.append("## Top 100 Largest Tracked Files")
    report_lines.append("")
    report_lines.append("| Path | Size MB |")
    report_lines.append("|---|---:|")
    for rel, size in largest_files:
        report_lines.append(f"| `{rel}` | {_human_mb(size)} |")

    report_lines.append("")
    report_lines.append("## Top 30 Largest Tracked Top-Level Directories")
    report_lines.append("")
    report_lines.append("| Directory | Size MB |")
    report_lines.append("|---|---:|")
    for directory, size in largest_dirs:
        report_lines.append(f"| `{directory}` | {_human_mb(size)} |")

    report_lines.append("")
    report_lines.append("## Duplicate Files by Content Hash")
    report_lines.append("")
    if dup_hashes:
        report_lines.append("| SHA256 | Count | Paths |")
        report_lines.append("|---|---:|---|")
        for digest, paths in dup_hashes[:50]:
            joined = "<br>".join(f"`{p}`" for p in paths[:8])
            suffix = "<br>...more" if len(paths) > 8 else ""
            report_lines.append(f"| `{digest}` | {len(paths)} | {joined}{suffix} |")
    else:
        report_lines.append("No duplicates found.")

    report_lines.append("")
    report_lines.append("## Duplicate Markdown/JSON Reports (name-level)")
    report_lines.append("")
    report_lines.append("| Basename | Count | Paths |")
    report_lines.append("|---|---:|---|")
    name_groups: dict[str, list[str]] = collections.defaultdict(list)
    for rel, _ in file_rows:
        suffix = Path(rel).suffix.lower()
        if suffix in {".md", ".json"}:
            name_groups[Path(rel).name].append(rel)
    for name, paths in sorted(name_groups.items(), key=lambda item: len(item[1]), reverse=True):
        if len(paths) < 2:
            continue
        joined = "<br>".join(f"`{p}`" for p in paths[:8])
        suffix = "<br>...more" if len(paths) > 8 else ""
        report_lines.append(f"| `{name}` | {len(paths)} | {joined}{suffix} |")

    report_lines.append("")
    report_lines.append("## Tracked Files Under Blocked Path Patterns")
    report_lines.append("")
    if blocked:
        for rel in sorted(blocked):
            report_lines.append(f"- `{rel}`")
    else:
        report_lines.append("- None")

    report_lines.append("")
    report_lines.append("## Candidate Tier C Artifacts (>2MB structured files)")
    report_lines.append("")
    report_lines.append("| Path | Size MB |")
    report_lines.append("|---|---:|")
    for rel, size in sorted(candidate_tier_c, key=lambda item: item[1], reverse=True):
        report_lines.append(f"| `{rel}` | {_human_mb(size)} |")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(report_lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        default="docs/research/reports/repo_bloat_inventory.md",
        help="Output markdown report path",
    )
    args = parser.parse_args()
    generate_report(Path(args.output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
